# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- options:
    allowNameChange: true
  path: deployment.patch.yaml
  target:
    kind: Deployment
- options:
    allowNameChange: true
  path: service.patch.yaml
  target:
    kind: Service
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          ephemeral-storage: 150Gi
  target:
    kind: Deployment
