apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: llama3-8b-vllm-inference-server
  name: llama3-8b-vllm-deployment
spec:
  selector:
    matchLabels:
      app: llama3-8b-vllm-inference-server
  template:
    metadata:
      labels:
        app: llama3-8b-vllm-inference-server
    spec:
      containers:
      - name: inference-server
        env:
          - name: MODEL_ID
            value: meta-llama/Meta-Llama-3-8B
