apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      containers:
      - name: inference-server
        env:
        - name: VLLM_XLA_CACHE_PATH
          value: "/data"
        volumeMounts:
        - name: model-data
          mountPath: /data/models
      volumes:
      - name: model-data
        persistentVolumeClaim:
          claimName: PVC_NAME